site:
  title: Skupper
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://pwright.github.io/mindmaps
  start_page: skupper::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: antora



ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true

output:
  dir: ./docs

asciidoc:
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true
  extensions:
    - asciidoctor-plantuml
    - ./lib/tab-block.js
